// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpearAutomation.Models.GCSS;

namespace SpearAutomation.Models.GCSS.Migrations
{
    [DbContext(typeof(SPEARGCSSContext))]
    [Migration("20190607041644_GcssInitialMigration")]
    partial class GcssInitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099");

            modelBuilder.Entity("SpearAutomation.Models.GCSS.Vehicle", b =>
                {
                    b.Property<int>("Tam");

                    b.Property<DateTime>("DateAvailable");

                    b.Property<int>("Location");

                    b.HasKey("Tam");

                    b.ToTable("Vehicle");
                });
#pragma warning restore 612, 618
        }
    }
}
