// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpearAutomation.Models.MOL;

namespace SpearAutomation.Models.MOL.Migrations
{
    [DbContext(typeof(SPEARMOLContext))]
    [Migration("20190607042625_MolInitialMigration")]
    partial class MolInitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099");

            modelBuilder.Entity("SpearAutomation.Models.MOL.Personnel", b =>
                {
                    b.Property<int>("MarineId");

                    b.Property<DateTime>("DateReturning");

                    b.Property<int>("Location");

                    b.HasKey("MarineId");

                    b.ToTable("Personnel");
                });
#pragma warning restore 612, 618
        }
    }
}
