// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpearAutomation.Models.MOL;

namespace SpearAutomation.Models.MOL.Migrations
{
    [DbContext(typeof(SPEARMOLContext))]
    partial class SPEARMOLContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SpearAutomation.Models.MOL.Personnel", b =>
                {
                    b.Property<int>("MarineId");

                    b.Property<int>("CertificationLevel");

                    b.Property<DateTime>("DateReturning");

                    b.Property<int>("Location");

                    b.HasKey("MarineId");

                    b.ToTable("Personnel");
                });
#pragma warning restore 612, 618
        }
    }
}
